### ISSUE TITLE
QOL - buy-N-units input exact amount (with twins)

### ISSUE THREAD

**Issue by tomeresk** [swarmsim/swarm#389]
Currently if I want to buy 1M of a unit before I have any twin upgrades I can just input that amount and get it.
Once I have twins x256 for example, if I want to buy 1M units I actually have to manually calculate it and put in 3907 (1M divided by 256 and rounded up).

Would be really nice to have some form of option to make that field buy the exact amount of units that I write.

For example:
If I put in 1,000,000 and have no twin upgrades, it will buy 1M units.
If i put in 1,000,000 and have x256 twin upgrade, it will make the division and round it up, actually buying only 3907, but I get roughly the 1M I originally wanted to buy.

Thanks!

**Comment by erosson** [comment]
thought I already had a bug for this; looks like I didn't. Thanks for creating it.

**Comment by Shoelace** [comment]
i thought so to... but it migth have just been a reddit comment..

thought.. how about 2 buy buttons..?  ie  a [buy units]  and a [buy twins]

**Comment by tomeresk** [comment]
Personally I can't think of a use case where I would prefer the current behavior over buying the exact amount. When I am looking to buy an arbitrary amount, I use the middle buy button or the buy max button. When I am looking to buy a precise amount I use the buy-N feature.

If you believe some people will use both for different cases then I agree 2 buy buttons might be best. Seems to me though that most people will pick one and stick with it so we can avoid more screen clutter by keeping only one.

**Comment by erosson** [comment]
an upcoming change will support this: input of '=1000' buys 1000 units after accounting for twins. input of '1000' still pays for 1000 units regardless of twins, like today.

why not two buy buttons? because there are a couple other magic symbols in this change, and a buy button for each one would add a lot of clutter and intimidate newbies. magic symbols in the input field are harder to learn, but won't confuse new or casual players, yet still give power-users more power.
