### ISSUE TITLE
buy-N-units input scientific-e notation wiping the number

### ISSUE THREAD

**Issue by tomeresk** [swarmsim/swarm#398]
There is quite an annoying bug when using scientific-e notation numbers to buy units, when I start typing a number and then write "e", the entire contents of the input are deleted in most cases (occasionally it works normally).
The only workaround I found is typing "e" followed by what needs to be after the e, and then going back to type the original number.

Happens on chrome (didn't try other browsers)

**Comment by jrynd** [comment]
Apparently there's some numerical validation happening on the field. If you don't type the "e", it works fine. If you type the "e" with nothing after it, it's an invalid number. I propose that the validator check if the last character is "e" and if so, assume there's a '0' after it.

**Comment by erosson** [comment]
I'm using Chrome and haven't ever seen this. 2 of you have, though; I believe you.

There's no validation for this in my code. AngularJS does some validation on this, but swarmsim's specifically dodging it by grabbing the element with jquery instead of letting angular do it: https://github.com/erosson/swarm/issues/271

My best guess is that angular's validation's getting triggered somehow. don't think I can kill this except by changing from input `type="number"` to `type="text"`, which has some unfortunate side effects (mobile keyboard, up/down arrows) that are probably worth the switch overall, with some other issues.

**Comment by erosson** [comment]
wait, you're right, this is totally broken. works with '1e[whatever]' but fails with '2e[whatever]', or any other leading number that's not 1. that's weird.
