### ISSUE TITLE
number format: log10(n)

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#421]
this might not be a bad idea

> A suggestion/wishlist item: For the choice of units to display, I think a useful alternative to scientific/engineering would be simply to display as log10 of the number -- given the exponential growth of many things, the logarithms should behave very nicely.

**Comment by KillaPL** [comment]
@erosson I was actually thinking about this and am glad that it's already there. If you point me at a direction in the code I could try to add this myself.

**Comment by KillaPL** [comment]
I managed to setup dev settings locally and play around with that idea. As a result, I no longer think it's useful in this form. The main issue with that is that having the numbers displayed as log10 alone is not very useful, people are not used to think in logarithms. It does not pass any useful information by itself and is confusing.

What might be useful, is an array of first, second and third differentials of the logs. I've had an idea about orchestrating my spendings in such way, that they would keep all third differentials at 0. However, there might be a problem with that too, since the growth is not actually exponential, but polynomial.

I would gladly spent some time playing with that idea and trying to write some plugin, that would create such table for me, If I was able to get hold on unit counts from javascript console. Is that possible?

**Comment by erosson** [comment]
> If you point me at a direction in the code

Sounds like you already found it, but for the record: https://github.com/erosson/swarm/blob/master/app/scripts/filters/bignum.coffee

> If I was able to get hold on unit counts from javascript console. Is that possible?

Sure, this post says how: https://www.reddit.com/r/swarmsim/comments/2t5oz9/unencrypted_version_of_save_readonly/cnvybr6

`angular.element(document.body).injector().get('game').countUnits()`

**Comment by erosson** [comment]
#440 will make this possible without bloating the list of options. closing this in favor of #440.
