### ISSUE TITLE
Scrollbar appears when clicking "More"

### ISSUE THREAD

**Issue by Allen-B1** [swarmsim/swarm#708]
When I click the "More" dropdown, a scrollbars appears and the page zooms out (on Android). This is mildly annoying.

**Comment by erosson** [comment]
Huh, that didn't used to happen. I was able to reproduce this just now on my phone, a few minutes into a new game. Thanks for the report.

**Comment by Allen-B1** [comment]
No problem

**Comment by erosson** [comment]
If the dropdown menu would fall off the right side of the screen, it should now adjust itself so its right edge lines up with the button, instead of its left. 

"wouldn't it be simpler to *always* make the right edge line up, instead of inspecting element widths?" Tried, but a line break can put "more..." on its own line, where the menu falls off the left instead.
